par(mfcol=c(2,2),mar=c(4,4,2,1),oma=c(0,0,2,0))
data1<-read.table("./Exploratory Analysis Week1/household_power_consumption.txt",header=TRUE,sep=";",na.strings = "?")
data2<-subset(data1,Date=="1/2/2007" | Date=="2/2/2007")
data2$Date<-as.Date(data2$Date,format="%d/%m/%Y")
hist(data2$Global_active_power,main="Global_Active_Power",xlab = "Global Active Power (kilowatts)",col="red")
data2$DateTime<-paste(data2$Date,data2$Time)
data2$DateTime<-as.POSIXct(data2$DateTime)
with(data2,plot(Sub_metering_1~DateTime,type="l",ylab = "Energy Sub Metering",xlab=""))
with(data2,points(Sub_metering_2~DateTime,type="l",col="red"))
with(data2,points(Sub_metering_3~DateTime,type="l",col="blue"))
legend("topright",lty=1,col=c("black","red","blue"),lwd=2,bty="n",cex=0.4,legend = c("sub_metering_1","sub_metering_2","sub_metering_3"))
with(data2,plot(Voltage~DateTime,type="l",ylab="Voltage",xlab="datetime"))
with(data2,plot(Global_active_power~DateTime,type="l",ylab="Global Active Power (kilowatts)",xlab=""))
dev.copy(png,"plot4.png",width=480,height=480)
dev.off()
